name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-24.04
    env:
      platform: linux-musl
      channel: stable
      target: x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Download cross binary
        run: ci/download_cross.bash $target $platform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Rust version
        run: ci/set_rust_version.bash $channel $target
      - name: Build
        run: ci/build.bash $PWD/cross $target
      - name: Run tests
        run: ci/test.bash $PWD/cross $target
      - name: Trigger lines of code counter re-deploy
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: ci/redeploy_lines_of_code_counter.bash
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOWS_PAT }}
